FROM node
# Instala tudo que é necessário para que o projeto do React funcione.
# Isso envolve executar o procedimento de npm install com o package.json
WORKDIR /usr/local/service
RUN     npm install -g npm@next-10
