FROM node
# Instala tudo que é necessário para que o projeto do React funcione.
# Isso envolve executar o procedimento de npm install com o package.json
WORKDIR /app
RUN     npm install -g npm@next-11
