name: digitovsky

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/local/service
    #command: [ "sh", "-c", "cd /usr/local/service && gradle bootRun --no-daemon" ]
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/usr/local/service
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "cd /usr/local/service && npm install && npm run dev -- --host"]
    depends_on:
      - backend