name: randomchess

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    command: [ "sh", "-c", "go mod tidy && CGO_ENABLED=1 go build -v -o server && ./server" ]
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/app
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "cd /app && npm install && npm start"]
    depends_on:
      - backend
